# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nwaynaturals

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_3d306c38650b441eb12fb88b02a3caf6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_252b7b628f024145b422b9be69d4f4bf }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_3d306c38650b441eb12fb88b02a3caf6 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nwaynaturals'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6fbb54aff5f94a55aea7e6af7446ffaa }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_3d306c38650b441eb12fb88b02a3caf6 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'